FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install specific version of NumPy
RUN pip install "numpy<2"

COPY utils ./utils
COPY nuclei/. .

# RUN export no_proxy="localhost"

# gunicorn app_producer:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:9021
CMD ["gunicorn", "app_producer:app", "--workers", "8", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:9030"]
